server:
  port: 8080


spring:
  application:
    name: nhn-academy-spring-boot-jpa
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379



api:
  account:
    url: http://localhost:8081  # 팀원이 만든 Account API 주소
#    url: http://172.24.101.208:8081
  task:
    url: http://localhost:8082
# 220.67.223.52




